Small tweaks (#6)
* Only attempt to add $repos if there any defined

We mainly use Helm in Concourse for spinning up short-lived services (Postgres, Redis etc) to run our tests against, and for these we use some super-simple Helm charts that we keep in a Github repo. So we don't ever add any Helm repos, hence the `if [ $repos ]` guard here (because doing `helm repo update` with no $repos causes an explosion)

* Bump the Helm version

I was getting

```
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

when it attempted the Helm deploy with 3.0.0

* Output an empty list if there's no static release name

This is how the existing Helm-2 resource does it

* Add a Makefile

Just to ease building and pushing the image